import React, { useEffect, useMemo, useState } from "react";
import "./style.css";

import type { FraudEnvelope, HistoryItem, StateJson, TraceFile } from "./lib/types";
import { fetchFraudProof, fetchHistory, fetchState, fetchTrace, openEvents } from "./lib/api";

import { Agents } from "./components/Agents";
import { Wallets } from "./components/Wallets";
import { Commitments } from "./components/Commitments";
import { Replay } from "./components/Replay";
import { Fraud } from "./components/Fraud";
import { Timeline } from "./components/Timeline";

function pairsToObj(pairs: [string, number][]) {
  const o: Record<string, number> = {};
  for (const [k, v] of pairs) o[k] = v;
  return o;
}

function commitmentsToObj(pairs: [string, number[]][]) {
  const o: Record<string, number[]> = {};
  for (const [k, v] of pairs) o[k] = v;
  return o;
}

export default function App() {
  const [state, setState] = useState<StateJson | null>(null);
  const [meta, setMeta] = useState<{ path: string; mtimeMs: number } | null>(null);

  const [system, setSystem] = useState("snake");
  const [selectedAgent, setSelectedAgent] = useState<string | null>(null);

  const [trace, setTrace] = useState<TraceFile | null>(null);
  const [traceLoading, setTraceLoading] = useState(false);
  const [traceStatus, setTraceStatus] = useState("");

  const [fraud, setFraud] = useState<FraudEnvelope | null>(null);
  const [fraudError, setFraudError] = useState<string | null>(null);

  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [live, setLive] = useState(true);

  const balances = useMemo(() => (state ? pairsToObj(state.balances) : {}), [state]);
  const commitments = useMemo(() => (state ? commitmentsToObj(state.commitments) : {}), [state]);

  async function refreshState() {
    const s = await fetchState();
    setState(s.state);
    setMeta(s.meta);
  }

  async function refreshHistory() {
    const h = await fetchHistory(250);
    if (h.ok) setHistory(h.items as HistoryItem[]);
  }

  useEffect(() => {
    (async () => {
      await refreshState();
      await refreshHistory();
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!live) return;

    const es = openEvents(async (evt) => {
      if (evt.type === "message") return;

      // any state/trace/fraud change: refresh state + history
      try {
        await refreshState();
        await refreshHistory();
      } catch {
        // ignore
      }
    });

    return () => es.close();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [live]);

  useEffect(() => {
    (async () => {
      if (!selectedAgent) {
        setTrace(null);
        setFraud(null);
        setFraudError(null);
        return;
      }

      setTraceLoading(true);
      setTraceStatus("loading trace");
      setFraud(null);
      setFraudError(null);

      try {
        const t = await fetchTrace(system, selectedAgent);
        setTrace(t.trace);
        setTraceStatus(t.meta.generated ? "trace generated by CLI" : "trace loaded");

        try {
          const fp = await fetchFraudProof(selectedAgent);
          setFraud(fp.proof);
          setFraudError(null);
        } catch (e: any) {
          setFraud(null);
          setFraudError(String(e?.message || e));
        }
      } catch (e: any) {
        setTrace(null);
        setTraceStatus(String(e?.message || e));
      } finally {
        setTraceLoading(false);
      }
    })();
  }, [selectedAgent, system, meta?.mtimeMs]);

  if (!state) {
    return (
      <div className="container">
        <h1>nets observer</h1>
        <div className="sub">Loading local nets state</div>
        <div className="card">
          <div className="small">
            If this is stuck, your state.json is not found. Set NETS_STATE_PATH when starting nets-web.
          </div>
        </div>
      </div>
    );
  }

  const commitmentRoot = selectedAgent ? (commitments[selectedAgent] || null) : null;

  return (
    <div className="container">
      <div className="row" style={{ justifyContent: "space-between", alignItems: "baseline" }}>
        <div>
          <h1>nets observer</h1>
          <div className="sub">
            Read only view of local nets state
            {meta ? <span className="pill" style={{ marginLeft: 10 }}>state: {meta.path}</span> : null}
          </div>
        </div>

        <div className="row">
          <span className="pill">system</span>
          <select value={system} onChange={(e) => setSystem(e.target.value)} style={{ width: 140 }}>
            <option value="snake">snake</option>
            <option value="chess">chess</option>
            <option value="rps">rps</option>
          </select>

          <button className="btn" onClick={() => setLive(v => !v)}>
            live: {live ? "on" : "off"}
          </button>
        </div>
      </div>

      <div className="grid">
        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <Agents
            balances={balances}
            bindings={state.bindings}
            selectedAgent={selectedAgent}
            onSelect={(a) => setSelectedAgent(a)}
          />
          <Wallets wallets={state.wallets} />
          <Commitments commitments={commitments} />
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <Replay trace={trace} loading={traceLoading} status={traceStatus} />
          <Fraud commitmentRoot={commitmentRoot} trace={trace} fraud={fraud} fraudError={fraudError} />
          <Timeline history={history} />
        </div>
      </div>
    </div>
  );
}
